/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "MenuDLG.h"
#include "MTouchDLG.h"
#include "STouchDLG.h"
// USER END

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0         (GUI_ID_USER + 0x00)
#define ID_BUTTON_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_1         (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
#define COLOR_W	GUI_LIGHTGRAY
#define COLOR_F GUI_MAKE_COLOR(0x002F2F2F)
#define COLOR_B GUI_ORANGE
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_BITMAP bmstouch;
extern GUI_CONST_STORAGE GUI_BITMAP bmmtouch;
extern GUI_CONST_STORAGE GUI_BITMAP bmmikroe;
extern GUI_CONST_STORAGE GUI_BITMAP bmmikroecap;
extern GUI_CONST_STORAGE GUI_BITMAP bmbg;
// USER ENDGUI_RED

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Menu", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Single-touch", ID_BUTTON_0, 133, 180, 200, 200, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Multi-touch!", ID_BUTTON_1, 467, 180, 200, 200, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static void _cb_Button(WM_MESSAGE * pMsg) {
	switch (pMsg->MsgId) {
	case WM_PAINT:
		GUI_SetAlpha(65);   // Set alpha value for drawing operations
		break;

	}
   BUTTON_Callback(pMsg);
   GUI_SetAlpha(0);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Menu'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, COLOR_W);
    // USER START (Optionally insert additional code for further widget initialization)
    WIDGET_EFFECT_Simple_SetColor(0, COLOR_F);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cb_Button);

    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, COLOR_B);
    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, COLOR_F);
    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, COLOR_F);
    BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, COLOR_B);
    BUTTON_SetFrameColor(hItem, COLOR_F);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    BUTTON_SetFocussable(hItem, 0);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmstouch, 20, 10);
    BUTTON_SetTextOffset(hItem, 0, 88);


    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    WM_SetHasTrans(hItem);
    WM_SetCallback(hItem, _cb_Button);

    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, COLOR_B);
    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, COLOR_F);
    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, COLOR_F);
    BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, COLOR_B);
    BUTTON_SetFrameColor(hItem, COLOR_F);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    BUTTON_SetFocussable(hItem, 0);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmmtouch, 20, 10);

    BUTTON_SetTextOffset(hItem, 0, 88);

    // USER END
    break;
  case WM_PAINT:
	  GUI_DrawBitmap(&bmbg, 0, 0);
	  GUI_DrawBitmap(&bmmikroecap, 75, 10);
	  GUI_DrawBitmap(&bmmikroe, 75, 403);
	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'STOUCH'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
    	  WM_HideWindow(hMenu);
    	  menu_state=STOUCH_DEMO;
    	  CreateSTouch();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'MTOUCH'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
    	 // hWin = pMsg->hWin;
    	  WM_HideWindow(hMenu);
    	  menu_state=MTOUCH_DEMO;
		  CreateMTouch();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMenu
*/
WM_HWIN CreateMenu(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
