/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "STouchDLG.h"
#include "MenuDLG.h"
#include <stdio.h>
// USER END

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0         (GUI_ID_USER + 0x00)
#define ID_BUTTON_0         (GUI_ID_USER + 0x01)
#define ID_BUTTON_1         (GUI_ID_USER + 0x02)
#define ID_TEXT_0         	(GUI_ID_USER + 0x04)
#define ID_DROPDOWN_0       (GUI_ID_USER + 0x05)
#define ID_RADIO_0         	(GUI_ID_USER + 0x06)
#define ID_SPINBOX_0        (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_0       (GUI_ID_USER + 0x08)
#define ID_SLIDER_0         (GUI_ID_USER + 0x09)
#define ID_PROGBAR_0        (GUI_ID_USER + 0x0A)
#define ID_LISTBOX_0        (GUI_ID_USER + 0x0B)
#define ID_TEXT_1         	(GUI_ID_USER + 0x0D)
#define ID_TEXT_2         	(GUI_ID_USER + 0x0E)
#define ID_TEXT_3         	(GUI_ID_USER + 0x0F)
#define ID_TEXT_4         	(GUI_ID_USER + 0x10)
#define ID_SCROLLBAR_0      (GUI_ID_USER + 0x11)
#define ID_TEXT_5         	(GUI_ID_USER + 0x12)
#define ID_EDIT_0         	(GUI_ID_USER + 0x13)
#define ID_TEXT_6         	(GUI_ID_USER + 0x14)
#define ID_BUTTON_2         (GUI_ID_USER + 0x15)
#define ID_TEXT_7         	(GUI_ID_USER + 0x16)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
// { TEXT_CreateIndirect, "Scrollbar", ID_TEXT_5, 373, 260, 80, 20, 0, 0x0, 0 },

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "STouch", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BTN1", ID_BUTTON_0, 25, 280, 80, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BTN2", ID_BUTTON_1, 695, 280, 80, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Dropdown", ID_TEXT_0, 25, 51, 80, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 25, 75, 80, 80, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 200, 75, 80, 60, 0, 0x1403, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_SPINBOX_0, 361, 75, 80, 45, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 540, 76, 99, 30, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 25, 427, 750, 31, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 155, 295, 490, 30, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 695, 76, 80, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Radio", ID_TEXT_1, 200, 51, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Spinbox", ID_TEXT_2, 360, 51, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Checkbox", ID_TEXT_3, 540, 51, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Listbox", ID_TEXT_4, 695, 51, 80, 20, 0, 0x0, 0 },
  { SCROLLBAR_CreateIndirect, "Scrollbar", ID_SCROLLBAR_0, 25, 365, 750, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Progbar", ID_TEXT_5, 380, 270, 80, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 329, 185, 144, 55, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Edit", ID_TEXT_6, 388, 165, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "x", ID_BUTTON_2, 772, 8, 22, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Test window objects", ID_TEXT_7, 315, 8, 220, 22, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char data[10]="";
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'STouch'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_ORANGE);
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, "Item 1");
    DROPDOWN_AddString(hItem, "Item 2");
    DROPDOWN_AddString(hItem, "Item 3");
    DROPDOWN_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "Option 1", 0);
    RADIO_SetText(hItem, "Option 2", 1);
    RADIO_SetText(hItem, "Option 3", 2);
    RADIO_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    SPINBOX_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Check");
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "Item 0");
    LISTBOX_AddString(hItem, "Item 1");
    LISTBOX_AddString(hItem, "Item 2");
    LISTBOX_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Scrollbar'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_32B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    // USER START (Optionally insert additional code for further widget initialization)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_WHITE);
    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
    BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_RED);
    BUTTON_SetFrameColor(hItem, GUI_WHITE);
    BUTTON_SetFont(hItem, GUI_FONT_24B_1);
    BUTTON_SetFocussable(hItem, 0);


	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetTextColor(hItem, GUI_ORANGE);
    // USER END
    break;
  case WM_PAINT:
    GUI_SetColor(GUI_GRAY_7C);
    GUI_FillRect(0,0,800,32);
    GUI_DrawRoundedFrame(0,0,800,480,0,5);
	break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'BTN1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
          int val=PROGBAR_GetValue(hItem);
          if(val>0)val--;
          PROGBAR_SetValue(hItem , val);
          sprintf((char*)data,"%04d",val);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          EDIT_SetText(hItem, data);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'BTN2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
          int val=PROGBAR_GetValue(hItem);
          if(val<100)val++;
          PROGBAR_SetValue(hItem , val);
          sprintf((char*)data,"%04d",val);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          EDIT_SetText(hItem, data);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'BTN1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
          // USER START (Optionally insert code for reacting on notification message)
      	  hItem = pMsg->hWin;
  		  WM_DeleteWindow(hItem);
  		  menu_state=MAIN_MENU;
  		  WM_ShowWindow(hMenu);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
          int val=DROPDOWN_GetSel(hItem);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          switch(val){
          case 0:EDIT_SetText(hItem, "item 1");
        	  break;
          case 1:EDIT_SetText(hItem, "item 2");
        	  break;
          case 2:EDIT_SetText(hItem, "item 3");
        	  break;
          }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
          int val=RADIO_GetValue(hItem);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          switch(val){
          case 0:EDIT_SetText(hItem, "option 1");
        	  break;
          case 1:EDIT_SetText(hItem, "option 2");
        	  break;
          case 2:EDIT_SetText(hItem, "option 3");
        	  break;
          }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SPINBOX_0: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SPINBOX_0);
    	  int val=SPINBOX_GetValue(hItem);
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          sprintf((char*)data,"%04d",val);
          EDIT_SetText(hItem, data);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    	  int val=CHECKBOX_IsChecked(hItem);
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    	  if(val)
    		  EDIT_SetText(hItem, "checked");
    	  else
    		  EDIT_SetText(hItem, "unchecked");
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    	  int val=SLIDER_GetValue(hItem);
          sprintf((char*)data,"%04d",val);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          EDIT_SetText(hItem, data);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
          PROGBAR_SetValue(hItem , val);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
          hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
          int val=LISTBOX_GetSel(hItem);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          switch(val){
          case 0:EDIT_SetText(hItem, "item 1");
        	  break;
          case 1:EDIT_SetText(hItem, "item 2");
        	  break;
          case 2:EDIT_SetText(hItem, "item 3");
        	  break;
          }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SCROLLBAR_0: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
    	  hItem = WM_GetDialogItem(pMsg->hWin, ID_SCROLLBAR_0);
    	  int val=SCROLLBAR_GetValue(hItem);
          sprintf((char*)data,"%04d",val);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
          EDIT_SetText(hItem, data);
          hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
          PROGBAR_SetValue(hItem , val);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSTouch
*/
WM_HWIN CreateSTouch(void);
WM_HWIN CreateSTouch(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
